[project]
name = "portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "djlint>=1.36.4",
    "flask>=3.1.1",
    "markdown>=3.8.2",
    "requests>=2.32.4",
]

[tool.uv.workspace]
members = [
    "temp",
]
